// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCYSU_XCADC0UCWEb9jVD1Gm5ImzQCMJus',
    appId: '1:955285183165:web:515c172303614a73b875d4',
    messagingSenderId: '955285183165',
    projectId: 'a-9018f',
    authDomain: 'a-9018f.firebaseapp.com',
    storageBucket: 'a-9018f.appspot.com',
    measurementId: 'G-DDFNTZHYBC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAFm_hMjd7ukRVM1ZjXUzqVv6VaF1_NVpo',
    appId: '1:955285183165:android:d0109e6cd17c5410b875d4',
    messagingSenderId: '955285183165',
    projectId: 'a-9018f',
    storageBucket: 'a-9018f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCHilTOLyIQ4iW7APqDS3Y9UqeZCYLLfUk',
    appId: '1:955285183165:ios:caa7c389bf222c9cb875d4',
    messagingSenderId: '955285183165',
    projectId: 'a-9018f',
    storageBucket: 'a-9018f.appspot.com',
    iosClientId: '955285183165-51lo2l1f3r33mcrbnt2ufa6fm23pbusj.apps.googleusercontent.com',
    iosBundleId: 'com.example.pfsi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCHilTOLyIQ4iW7APqDS3Y9UqeZCYLLfUk',
    appId: '1:955285183165:ios:b0d525d68b644060b875d4',
    messagingSenderId: '955285183165',
    projectId: 'a-9018f',
    storageBucket: 'a-9018f.appspot.com',
    iosClientId: '955285183165-656hkf6iu4vv6muqgmcmbq3tn3d7jkbh.apps.googleusercontent.com',
    iosBundleId: 'com.example.pfsi.RunnerTests',
  );
}
